<a href="https://colab.research.google.com/github/Iqbalnm786/DATA-SCIENCE-AND-BIG-DATA/blob/main/simple_numpy_assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assessment **1** (Easy):

---



In [1]:
# 1️⃣ Create a NumPy array from this list:
# [4, 8, 12, 16, 20]
# → Use np.array()

import numpy as np
np.array([4, 8, 12, 16, 20])

array([ 4,  8, 12, 16, 20])

In [2]:
# 2️⃣ Generate an array of numbers from 1 to 30 with a step of 3
# → Use np.arange()

np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [4]:
# 3️⃣ Create an array of 5 evenly spaced numbers between 0 and 1
# → Use np.linspace()

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# 4️⃣ Create a 3×3 matrix of zeros and a 2×4 matrix of ones
# → Use np.zeros() and np.ones()

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:

np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# 5️⃣ Reshape this array into 3 rows and 2 columns:
# [1, 2, 3, 4, 5, 6]
# → Use np.reshape()

arr=np.array([1, 2, 3, 4, 5, 6])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
# 6️⃣ Find the sum, mean, max, and min of the array:
# [10, 20, 30, 40, 50]
# → Use np.sum(), np.mean(), np.max(), np.min()

arr=np.array([10, 20, 30, 40, 50])
np.sum(arr)

np.int64(150)

In [23]:
arr=np.array([10, 20, 30, 40, 50])
np.mean(arr)

np.float64(30.0)

In [24]:
arr=np.array([10, 20, 30, 40, 50])
np.max(arr)

np.int64(50)

In [25]:
arr=np.array([10, 20, 30, 40, 50])
np.min(arr)

np.int64(10)

In [26]:
# 7️⃣ Sort this array:
# [9, 2, 7, 1, 6]
# → Use np.sort()

arr=np.array([9, 2, 7, 1, 6])
np.sort(arr)

array([1, 2, 6, 7, 9])

# Assessment 2 (Easy):

---



In [27]:
# 1️⃣ Generate an array of 5 random integers between 10 and 50
# → Use np.random.randint()

np.random.randint(10,50)

35

In [28]:
# 2️⃣ Generate a 2×3 matrix of random values between 0 and 1
# → Use np.random.rand()

np.random.rand(2,3)

array([[0.01259098, 0.42347714, 0.82137583],
       [0.13801829, 0.10492434, 0.57355576]])

In [31]:
# 3️⃣ Combine these two arrays into one:
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# → Use np.concatenate()

a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate([a,b])


array([1, 2, 3, 4, 5, 6])

In [33]:
# 4️⃣ From this array:
# arr = np.array([3, 7, 2, 7, 9, 2, 3])
# Find the unique values.
# → Use np.unique()

arr=np.array([3, 7, 2, 7, 9, 2, 3])
np.unique(arr)

array([2, 3, 7, 9])

In [38]:
# 5️⃣ Using this matrix:
# A = np.array([[1, 2],
#               [3, 4]])
# Calculate its transpose.
# → Use A.T or np.transpose()
A = np.array([[1, 2],
              [3, 4]])
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [39]:
# 6️⃣ Perform matrix multiplication:
# A = np.array([[1, 2],
#               [3, 4]])
# B = np.array([[5, 6],
#               [7, 8]])
# → Use np.dot(A, B)
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [40]:
# 7️⃣ Find the indices where elements of this array are greater than 50:
# arr = np.array([12, 67, 45, 89, 23])
# → Use np.where()

arr = np.array([12, 67, 45, 89, 23])
np.where(arr>50)


(array([1, 3]),)